version: '3.3'

services:
  backendchat:
    container_name: backendchat
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongod
  mongod:
    container_name: mongod
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null